### ISSUE TITLE
Repo - search not working in some cases

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#17] opened 2015-08-08 18:07 UTC
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

·         Some offers came up in categories, however when the person went to search the name of the company, they couldn’t find it (for example “Fedex” does not show if searched but will come up in the area… and if you search it by merchant, it says “no physical locations for this merchant”

**Comment by brandplysreese** [comment] 2015-08-11 00:43
duplicate of https://github.com/Brandply/brandply1-1/issues/69

**Comment by brandplysreese** [comment] 2015-08-11 00:43
This issue was moved to Brandply/brandply1-1#102

**Closed as completed by brandplysreese** 2015-08-11 00:43 UTC
