### ISSUE TITLE
Login window is covering new account fields

### ISSUE THREAD

**Issue by pfr1990** [Brandply/publicissues#22] opened 2015-08-10 11:30 UTC
Platform: Pc Windows 10
 Browser: Microsoft Edge
 URL of page: https://archer.brandplydev.com/
 Organization or Member Login
 User: archer
 Password: 1234567
 Description of Problem: 

When trying to create new account the LOGIN window is covering some fields. Its dissapearing only when I click on LOGIN again.

Here are the steps that reproduce the problem:

1) Go to arche.brandlydev.com in your browser
2) Enter ZipCode when prompted : 84062
3) Click on LOGIN and choose Activate Account
4) Click on LOGIN to hide window

Screen shot:

![image](https://cloud.githubusercontent.com/assets/13362917/9170517/eaf5965e-3f63-11e5-9036-1a39cd8d16e4.png)

**Comment by pfelsted** [comment] 2015-08-10 16:31
This is a duplicate of https://github.com/Brandply/publicissues/issues/8

**Closed as completed** 2015-08-10 16:48 UTC
Labels: duplicate
